### ISSUE TITLE
Blindsight integration

### ISSUE THREAD

**Issue by wsargent** [afsalthaj/safe-string-interpolation#66]
I'm evaluating options for a `Message` DSL that takes a string and ensures that it has safe representation: https://github.com/tersesystems/blindsight/issues/86

safe-string-interpolation looks great, but it has a couple of outstanding issues -- having no dependency on scalaz, [2.13 support](https://github.com/afsalthaj/safe-string-interpolation/issues/38) and [minimal runtime costs](https://github.com/afsalthaj/safe-string-interpolation/issues/36) in particular are things I'm interested.  Are you actively working on this project?

**Comment by afsalthaj** [comment]
@wsargent thanks for question! . I am trying to pull this library to make use of magnolia library and have a separate module dependency for scalaz and cats data types. 

I am currently busy with zio-config library but I can start working on these issues if it’s blocking you. Thanks !

**Comment by afsalthaj** [comment]
Still busy with zio-config and a few other talks. I will get back to implementing magnolia only next to next month

**Comment by wsargent** [comment]
It's okay, I [got it working](https://tersesystems.github.io/blindsight/usage/interpolation.html).
